### ISSUE TITLE
Uplaod dialog is looping

### ISSUE THREAD

**Issue by julz0815** [thatsjet/Send2Mars#3]
The video shows that that the upload dialog is looping if you do not hit close once. Tested on MacBook Pro OS X 10.10.5 and Chrome  47.0.2526.106 (64-bit).

As git doesn't allow videos you will find it here: https://www.dropbox.com/s/f1luf4vnec8evh3/2016-01-05%2012.40.52.mov?dl=0

**Comment by pdxpoppadaddy** [comment]
Awesome! Thanks for clear bug report.

To clarify: *After pressing the upload button the dialog closes. Send2Mars re-opens the dialog modal window. Only the close button ceases the process.*
